### PR TITLE
Port input handler replacing HID driver

### PR DESCRIPTION
**Pull request by kitten**
> [!NOTE]
> This is just a draft for illustrative purposes. There's probably some drawbacks to this, but it's interesting enough that I wanted to port it and show what this port does

While browsing I also found this fork/port (I believe originally of `leetmouse` as well with some changes): [maccel](https://github.com/Gnarus-G/maccel)

This fork doesn't seem to exactly share the same goals as yours, but it has found a very interesting solution to the problem of some HID devices not being handled as precisely as the kernel does it. By registering a virtual input device and receiving inputs via an input handler from connected HID devices (from the built-in drivers as far as I understand), they're scaling inputs then copying them over to the virtual device.

`maccel` itself doesn't seem to have expanded on the acceleration code as throughly as you have here  and made different choices in the fixed point changes. The GUI doesn't match up as nicely with Rawaccel, so I was pretty interested to instead port their input handler to `yeetmouse`.

For the original code, see: https://github.com/Gnarus-G/maccel/blob/982624e1de7971a4ac937ba5b5e7b6961610497c/driver/input_handler.h

The main thing I wanted to figure out is actually also whether the virtual input device is redundant, i.e. whether we can use the `input_handler` to simply modify the reported `x, y, wheel` values on the original `input_dev` and remove `virtual_input_dev`

### CODE REVIEW

**Comment by AndyFilter** [comment]
This approach looks like a very clean *solution* that doesn't involve any human interaction. I actually wanted to tackle this problem in a very different way, but I just never got to it mostly because I never really experienced this issue. The only device that wasn't automatically registered by the driver was my *Arduino Pro Micro*, that I used to reliably test different acceleration curves, and it makes sense, because it's not really a HID device (it just *simulates* to be one).

My idea was to allow user (through the GUI) to manually select HID devices to bind to the driver. In this scenario the binding would be done with the already existing `bind.sh` script.

The solution you provided is a great addition to the code, but first I'd have to check the performance overhead it introduces (which will not be trivial). Because from what I understand this virtual device takes all the HID events (**which happen thousands of times per second**) and forwards them to the correct part of the driver. And if that's the case, even small performance hits would be noticeable. If I'm somehow mistaken and the code runs only once (for every device) then, I see no issue with it.

Though if it was possible to skip the part of the virtual driver (`virtual_input_dev`), then I'd be an awesome addition.

At the end though, I'll still have to add the manual device assignment option because, as we all know, machines aren't perfect, and I'd rather give the user control over which devices are bound to which driver.

**Comment by kitten** [comment]
I think `maccel` does load both "drivers", but I don't think they implemented a mode to use both simultaneously (?) It's certainly possible though
So far, their docs claim that the latency difference is minimal, but I have no idea to verify that with real world measurements, and I'm not sure how they arrived at these measurements in particular either 😅 https://github.com/Gnarus-G/maccel/blob/dedaa97e9b9a4dc2d513921c6232a893033bc5c3/TWO_IMPLEMENTATIONS.md

I've been playing around with some ways of trying to bypass the input handler logic and to force the event to either be treated normally or be re-issued on the devices that are already bound to the appropriate drivers. So far no luck though. My experience with the Linux Input subsystem is basically zero, so I'm just going by trial and error so far.
I also haven't looked at whether there's an alternative approach that allows us to use the existing `usbhid` driver while modifying its events without `input_handler`s, but it's been hard to dig up enough documentation on that.

I'll see if I can find some more time for this in the coming weeks, for now, I'm testing the `input_handler` to see if it's stable.

**Comment by kitten** [comment]
just a quick update, so it's clear what I'm looking into next ✌️ 

after several unsuccessful attempts using `input_handler.filter` and `input_handler.match`, looking at the implementation of the input sub system, it makes more sense to look into whether modifying the `vals` (events) in `input_handler.events` directly: https://github.com/torvalds/linux/blob/c964ced7726294d40913f2127c3f185a92cb4a41/drivers/input/input.c#L2537-L2628

The only remaining question then would be what purpose `input_handler.event` serves. I've seen it used in `evdev`, but in the current version it seems to be gone. Maybe it's not needed https://github.com/torvalds/linux/blob/c964ced7726294d40913f2127c3f185a92cb4a41/drivers/input/evdev.c#L1417-L1425
The documentation on it is very sparse but nothing seems to imply that it's needed. Maybe just a shortcut for iterating over `vals` in `events` 🤷 https://www.kernel.org/doc/html/v4.15/driver-api/input.html#c.input_handler

This all assumes that it's actually possible to use these handlers to modify the events and that `input_handler`s actually intercept this data entirely before it reaches other subsystems or outputs.
If that's all true though, it's certainly possible to write this without a virtual input device, which would be my preference and criteria for this to be reliable

---

On a separate note, I have another branch where I've restored the driver code back to aligning with `drivers/hid/usbhid/usbmouse.c` in the Linux kernel (with slight tweaks). That gave me a nice starting point to better understand where the HID descriptor parser code comes in.

Looking at it, and knowing that a USB dongle causes trouble for me, I already looked at the raw HID descriptor data before (with the instructions from `leetmouse`'s repo). However, I found the HID descriptor data to basically be as expected, which is also why modifying `NUM_USAGES` didn't change the situation for me.

I basically suspect that there's some subtle bugs in the HID descriptor parser. It obviously also omits some cases, but I think the tl;dr is that it doesn't handle some important edge cases.

I'd still prefer to explore the virtual-device-less `input_handler` approach instead. After all, it'd use Linux's defined quirks and HID descriptor fix ups, and the usual `usbhid` drivers. Also with the virtual-device and using it over the last few days, I haven't found any issues. But failing that, I might try to debug the HID descriptor parser

**Comment by kitten** [comment]
Update:
> after several unsuccessful attempts using input_handler.filter and input_handler.match, looking at the implementation of the input sub system, it makes more sense to look into whether modifying the vals (events) in input_handler.events directly:
I think I managed to do this, finally 😅 I'll close this PR and will work on a replacement when I've got this all in shape

**Comment by Gnarus-G** [comment]
>  difference is minimal, but I have no idea to verify that with real world measurements, and I'm not sure how they arrived at these measurements in particular either 😅 https://github.com/Gnarus-G/maccel/blob/dedaa97e9b9a4dc2d513921c6232a893033bc5c3/TWO_IMPLEMENTATIONS.md
>
 
Nah you're definitely right to be skeptical of the benchmark results, I am too lowkey. I'm glad to be able to not need the virtual device.

Here is the script I created to benchmark, for anyone who still cares:

https://github.com/Gnarus-G/maccel/tree/dedaa97e9b9a4dc2d513921c6232a893033bc5c3/bench

I'm so glad someone else is taking this on seriously. Linux is hard.

**Pull request closed without merging**
